logging:
  level:
    org.springframework: INFO

security:
  basic:
    enabled: false

  oauth2:
    client:
      clientId: 6e1cf7b4-b107-42b3-9435-8fda70726c6a
      clientSecret: 6y4FUuP9BfAXeVqguNKT0ofToIwN5RdB1PaUvx_nCMiQbH9NeGq3pp0jQB9zOQ0APOxEbodzJXp-8RVux6318A
      username: pwfatut
      password: pwfatut
      scope: fint-client
      accessTokenUri: https://namidp01.rogfk.no/nidp/oauth/nam/token

fint:
  felleskomponent:
    uri: https://beta.felleskomponent.no
